# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f1e758e84095a5b5b52de031a15742c6b47325c2247ce80312cc6d819d2709d59d4e62abcae362589759a8b5178c72848b72e77f80c288ca67f7e3178e1c065

test:
  secret_key_base: 3dbc51103f8acfd6840a93993ed5652089877f5ce0e61de152ef50211296f9a177ee67e6c0058e660fee2d73ea769403200cc9d9c858bb0ac76d6d69d59e637c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
